# pytest.ini
[pytest]
pythonpath = .
addopts =
    -ra -q
    --cov=.
    --cov-report=term-missing
    --cov-branch
    --cov-fail-under=70
    --cov-config=pytest.ini
testpaths = tests
filterwarnings=
    ignore:.*distutils.*:DeprecationWarning

[coverage:run]
branch = True
source=
    au_ootp_tournament_utilities_v2
    utils
omit =
    */utils/view_utils/*
    *\utils\view_utils\*
    */tests/*
    *\tests\*
    */utils/data_utils/*
    *\utils\data_utils\*
    */utils/dialog_utils/*
    *\utils\dialog_utils\*
    *\utils\data_vis_utils\*
    */utils/data_vis_utils/*
    */utils/stats_utils/generate*
    *\utils\stats_utils\generate*

[coverage:report]
show_missing = True
skip_covered = True
fail_under = 70
