# Overall Card Value Background Colors
IRON_BACKGROUND_COLOR='#434343'
BRONZE_BACKGROUND_COLOR='#732d10'
SILVER_BACKGROUND_COLOR='#68768a'
GOLD_BACKGROUND_COLOR='#e49b34'
DIAMOND_BACKGROUND_COLOR='#25818f'
PERFECT_BACKGROUND_COLOR='#1b1e1c'

# Overall Card Value Font Colors
IRON_FONT_COLOR='#fefefe'
BRONZE_FONT_COLOR='#fefefe'
SILVER_FONT_COLOR='#fefefe'
GOLD_FONT_COLOR='#fefefe'
DIAMOND_FONT_COLOR='#fefefe'
PERFECT_FONT_COLOR='#f1a92e'

# Overall Card Value Border Colors
IRON_BORDER_COLOR='#000000'
BRONZE_BORDER_COLOR='#000000'
SILVER_BORDER_COLOR='#000000'
GOLD_BORDER_COLOR='#000000'
DIAMOND_BORDER_COLOR='#000000'
PERFECT_BORDER_COLOR='#1b1e1c'

